### ISSUE TITLE
App loading screen time & LocationModal

### ISSUE THREAD

**Issue by Heartheater** [chingu-voyages/v8-geckos-team-12#56]
When I start up the app, it gets my location from the browser and then immediately shows me the LocationModal, telling me "location was unavailable from browser". 
Then, after a few seconds, the app seems to process that it _already has_ my location data, and displays the rest of the app as it should.

The problem is that it initially shows me "location unavailable" for a few seconds after the loading screen passes. I'm not sure if anyone else is seeing this happen, but I think it should be fixed if possible.

**Comment by chrisczach** [comment]
I wasn't able to replicate the issue, is it an intermittent issue? I looked over the code and saw one part that could possibly cause the location modal to flash for a few milliseconds before the rest of the app is rendered. I changed that part and pushed to development, see if the issue is still coming up on your computer.

**Comment by Heartheater** [comment]
It's strange, I don't see it happening anymore when I use Google Chrome but when I use Firefox to open the website, it still flashes the location modal. I took a short video of it happening:
https://www.youtube.com/watch?v=BhAXRLI8WPw&feature=youtu.be

**Comment by chrisczach** [comment]
That's weird, it hangs on the location screen for a while, try clearing the cache on firefox and try it again.

**Comment by Heartheater** [comment]
I cleared the cache, that seems to have fixed it. Thanks for your help.
