### ISSUE TITLE
Reddit Feed Not working on Firefox

### ISSUE THREAD

**Issue by Manjilan** [chingu-voyages/v8-geckos-team-12#60]
We seem to have an issue with the App not loading the reddit feed on Firefox. May be its some kind of compatibility issue??

**Comment by helloRupa** [comment]
The autosuggestions do not appear, nor do the results for the selected feed.

**Comment by Heartheater** [comment]
When I visit the site with Firefox, these are the errors that I see pop up in the console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://www.reddit.com/r/javascript/.json. (Reason: CORS request did not succeed). [[Learn More]](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default)

> The resource at “https://www.reddit.com/r/javascript/.json” was blocked because content blocking is enabled. [[Learn More]](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Tracking_Protection?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)

**Comment by Heartheater** [comment]
I just tried disabling content blocking on Firefox and now the Reddit feed is showing up fine. Maybe it was just because of Firefox's content blocking feature?

**Comment by chrisczach** [comment]
I might just put the reddit api calls into a lambda function, should fix this issue and any other cors issues that might come up. Are any of the other api calls being affected by disabling tracking? We should move those over also if there are any issues.

**Comment by Manjilan** [comment]
The weather API seems to be working fine. Occasionally the news section does not show up but that happens rarely..

**Comment by chrisczach** [comment]
I created a pull request if someone can check if it works on firefox.

[Deploy Preview](https://5cb77f9b45ea3400084957dc--geckos.netlify.com/)

#64

**Comment by Manjilan** [comment]
It is working now with a 2 sec timeout...

**Comment by chrisczach** [comment]
Try it now, the app was rendering either the loading animation or the main app instead of loading both at the same so fetching wasn't happening until after the loading animation finished. Most of the other api's are pretty quick so it wasn't a big deal, reddit's api seems pretty slow. I thought that putting it into a lamba function and having a couple extra hops was causing an issue but it was only adding about 100ms compared to making a call to reddit's api directly, it was taking almost a full second to get a json back from their api.

[Updated Deploy Preview](https://5cb788e2783d750007fb2822--geckos.netlify.com/)

**Comment by helloRupa** [comment]
It is working for me now in Firefox without having to change any of the privacy settings. It's also faster than before.
